In [1]:
# import library
import numpy as np

In [3]:
# create empty array
arr=np.array([])
arr
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# create numpy array using list
list=[103,104,105,147,199]
arr=np.array(list)
print(arr)
print(type(arr))

[103 104 105 147 199]
<class 'numpy.ndarray'>


In [6]:
#create numpy array using tuple
tuple=("blue","green","orange","black")
arr=np.array(tuple)
arr

array(['blue', 'green', 'orange', 'black'], dtype='<U6')

In [7]:
arr=np.array(("ff","jj"))
arr

array(['ff', 'jj'], dtype='<U2')

In [8]:
# 1-D array
arr=np.array([1,2,3,4,5,6,7,8,9])
print("dimention of array is",arr.ndim)
print("number of elements are",arr.size)
print("data type of array elements",arr.dtype)
print("type of an object ",type(arr))
print("shape of an array",arr.shape)

dimention of array is 1
number of elements are 9
data type of array elements int32
type of an object  <class 'numpy.ndarray'>
shape of an array (9,)


In [14]:
# 2 D ARRAY
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("dimention of array is",arr.ndim)
print("number of elements are",arr.size)
print("data type of array elements",arr.dtype)
print("type of an object ",type(arr))
print("shape of an array",arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimention of array is 2
number of elements are 9
data type of array elements int32
type of an object  <class 'numpy.ndarray'>
shape of an array (3, 3)


In [17]:
# 3 d array
arr=np.array([[[1,2,3]]])
print("dimension of an array",arr.ndim)

dimension of an array 3


In [21]:
# 4 -d array
arr=np.array([1,2,3,4],ndmin=4)
print(arr)

[[[[1 2 3 4]]]]


In [24]:
# how to difine datatype while creating array
arr=np.array([1,2,3,4],dtype="float")
arr

array([1., 2., 3., 4.])

# type casting

In [25]:
arr=np.array([3.4,5,7,8.9,7,7.5,75])
arr

array([ 3.4,  5. ,  7. ,  8.9,  7. ,  7.5, 75. ])

In [26]:
arr.astype("int")

array([ 3,  5,  7,  8,  7,  7, 75])

# indexing and slicing

In [27]:
arr=np.array([101,102,103,104,105,106,107,108])
print(arr)

[101 102 103 104 105 106 107 108]


In [28]:
# fetch 103
arr[2]

103

In [29]:
arr[6]

107

In [30]:
arr[1:5]

array([102, 103, 104, 105])

In [33]:
arr[1::2]

array([102, 104, 106, 108])

In [34]:
# how to reverse numpy array
arr[::-1]

array([108, 107, 106, 105, 104, 103, 102, 101])

# indexing and slicing in 2d

In [36]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### fetch rows

In [37]:
# fetch first row
arr_2d[0]

array([1, 2, 3])

In [38]:
# 2nd row
arr_2d[1]

array([4, 5, 6])

In [39]:
# fetch first and second row
arr_2d[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr_2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# fetch 1st and 3rd row
arr_2d[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [46]:
# fetch 1st coloumn
arr_2d[:,[0]]

array([[1],
       [4],
       [7]])

In [47]:
# fetch thrid column
arr_2d[:,[2]]

array([[3],
       [6],
       [9]])

In [48]:
# fetch 1st and 3d column
arr_2d[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [49]:
# fetch first and second column
arr_2d[:,[0,1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [50]:
# using slicing
arr_2d[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [54]:
arr_2d[1:3,1:3] #using slicing

array([[5, 6],
       [8, 9]])

In [55]:
arr_2d[[1,2],[1,2]]

array([5, 9])

In [57]:
arr_2d[1:3,0:2]

array([[4, 5],
       [7, 8]])

# Arithmetic operations

In [59]:
A=np.array([10,20,30,40,50])
B=np.array([5,2,3,4,5])

In [60]:
# add
A+B

array([15, 22, 33, 44, 55])

In [61]:
# MULL
A*B

array([ 50,  40,  90, 160, 250])

In [63]:
# square
A**2

array([ 100,  400,  900, 1600, 2500])

In [64]:
# matrix maltiplication
A@B

590