# Build in function

## arange

In [1]:
import numpy as np

In [2]:
# generate array which includes values from 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#  generate values from 10 to 20
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
# genarate first 5 even number
np.arange(4,41,4)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [5]:
# multiple of 4
np.arange(4,41,4)

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

## linspace

In [6]:
# linspace generate linearly spaced values within a given range
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [7]:
np.linspace(1,2,retstep=True)  # retset will give diiference

(array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
        1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
        1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
        1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
        1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
        1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
        1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
        1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
        1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
        1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ]),
 0.02040816326530612)

In [8]:
# generate 10 linearly spaced values between 1 and 100
np.linspace(1,100,num=10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [10]:
# 1 to 1000   five linear spacing
np.linspace(1,1000,5,retstep=True)

(array([   1.  ,  250.75,  500.5 ,  750.25, 1000.  ]), 249.75)

## zeros

In [11]:
# it is used to generate 1-d or 5-d array with all values zero


In [12]:
# generate an 1-d array with 5 element as zero
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# generate 2-d array which has  3 rows and 4 coloumn
np.zeros((3,4))   # for 2d array 2 brackets

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# ones
* ones is used to generate 1d or 2d array with all elements as 1

In [14]:
# 1d array with 10 elements as ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones(10,dtype="int")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
# generate 2d array with 5 rows and 3 columns
np.ones((5,3,),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## eye
* it is used to generate identity matrix
* it generate only 2-d array
* it will not generate 1-d array

In [19]:
np.eye(2,2) # generates identity matrix with order (2,2)

array([[1., 0.],
       [0., 1.]])

In [20]:
# generate identity matrix of order(3,4)
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# full
it is used to generate 1-d or 2d array with same elements

In [22]:
 np.full(3,5)

array([5, 5, 5])

In [23]:
# create 2-d array with (3,4) with all values as 10
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

# random

In [26]:
# create an array which includes 4 random numbers between 0 to 1
np.random.rand(4)

array([0.11537952, 0.03849679, 0.03918023, 0.01749147])

In [28]:
# genarate 10 random number between 0 to 1
np.random.rand(10)

array([0.97233146, 0.66406302, 0.34988671, 0.34089916, 0.92966423,
       0.62471366, 0.74456006, 0.20758699, 0.94702649, 0.12969351])

In [29]:
# generate 2 -d array which includes 10 random number between 0 to 1
np.random.rand(5,2)

array([[0.51481602, 0.11444513],
       [0.5399948 , 0.20615681],
       [0.06537197, 0.8946913 ],
       [0.13773178, 0.30936207],
       [0.62568496, 0.46768967]])

### randn
randn generate 1-d and 2-d array which includes random normally distributed values

In [30]:
# generate an array which include 10 random normal numbers
np.random.randn(10)

array([-9.40151897e-01,  7.67053751e-01,  4.42606857e-02, -3.14493402e-01,
       -1.15542135e-01,  1.79659414e-04,  3.87043994e-01,  5.94440365e-01,
        1.91502048e-01, -6.57529639e-01])

In [31]:
# generate 2-d array of an order (3,4) which includes random normal number
np.random.randn(3,4)

array([[ 1.34388887,  2.03343796, -0.67852958, -0.65586217],
       [ 1.5964281 ,  0.13084633,  0.43278739, -1.49408905],
       [ 2.21525501,  1.46682437,  0.48676281, -0.10095944]])

## randint
it is used to generate random integer between any interval

In [32]:
# generate 10 random number between 1 to 100
np.random.randint(1,100,10)

array([91, 44, 15, 28, 14, 33, 26, 73,  5, 32])

In [33]:
np.random.randint(1,100,(5,3))

array([[81, 33, 28],
       [ 8, 48, 67],
       [17, 80, 71],
       [33, 17, 73],
       [13, 29, 25]])